# Generated by Django 3.2.8 on 2021-10-29 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField()),
                ('payment_status', models.BooleanField()),
                ('date', models.DateField(default=datetime.date(2021, 10, 29))),
                ('total_price', models.FloatField()),
                ('profit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('barcode_no', models.IntegerField()),
                ('stock_left', models.IntegerField()),
                ('selling_price', models.FloatField()),
                ('cost_price', models.FloatField()),
                ('category', models.CharField(max_length=5)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('margin', models.FloatField()),
            ],
        ),
    ]
